name: Android Fastlane CI

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      ANDROID_SDK_ROOT: /usr/local/android-sdk
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    steps:
      # 1️⃣ Check out code
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Bundler
        run: |
          gem install bundler
          bundler -v

      # 2️⃣ Set up Java 17 (required for AGP 8+)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Set up Ruby for Fastlane
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      # 4️⃣ Install Fastlane dependencies
      - name: Install Fastlane
        run: |
          gem install fastlane -NV
          fastlane --version

      # 5️⃣ Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6️⃣ Set up Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 7️⃣ Run Fastlane lane (example: `fastlane android beta`)
      - name: Run Fastlane
        run: |
          ls 
          cd android
          ls
          fastlane build build_type:qa 

