name: Android Fastlane CI

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Setup Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # 4️⃣ Install Fastlane (user-level to avoid permissions)
      - name: Install Bundler & Fastlane
        run: |
          gem install bundler --user-install
          gem install fastlane --user-install
          # Add user gem bin path to PATH for subsequent steps
          echo "export PATH=$HOME/.local/share/gem/ruby/3.2.0/bin:$PATH" >> $GITHUB_ENV

      # 5️⃣ Set up Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 6️⃣ Run Fastlane lane
      - name: Run Fastlane
        run: |
          ls 
          fastlane build build_type:qa

